### ISSUE TITLE
Kitchen test throws error

### ISSUE THREAD

**Issue by davidobrien1985** [pendrica/kitchen-azurerm#22]
Hi,

I am following, at least I believe I do, your how to to the letter.
However, when running `kitchen test` I get the following error:

```
➜  chef git:(master) ✗ kitchen test
-----> Starting Kitchen (v1.4.2)
-----> Cleaning up any prior instances of <default-windows2012-r2>
-----> Destroying <default-windows2012-r2>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #destroy action: [Tenant id cannot be nil]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

The `kitchen.log` is this:
```
I, [2016-02-23T22:34:00.598755 #64853]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.2)
I, [2016-02-23T22:34:01.419954 #64853]  INFO -- Kitchen: -----> Cleaning up any prior instances of <default-windows2012-r2>
I, [2016-02-23T22:34:01.421250 #64853]  INFO -- Kitchen: -----> Destroying <default-windows2012-r2>...
E, [2016-02-23T22:34:01.425477 #64853] ERROR -- Kitchen: ------Exception-------
E, [2016-02-23T22:34:01.425516 #64853] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-02-23T22:34:01.425536 #64853] ERROR -- Kitchen: Message: Failed to complete #destroy action: [Tenant id cannot be nil]
E, [2016-02-23T22:34:01.425552 #64853] ERROR -- Kitchen: ---Nested Exception---
E, [2016-02-23T22:34:01.425567 #64853] ERROR -- Kitchen: Class: ArgumentError
E, [2016-02-23T22:34:01.425621 #64853] ERROR -- Kitchen: Message: Tenant id cannot be nil
E, [2016-02-23T22:34:01.425675 #64853] ERROR -- Kitchen: ------Backtrace-------
E, [2016-02-23T22:34:01.425699 #64853] ERROR -- Kitchen: /Users/dobrien/.chefdk/gem/ruby/2.1.0/gems/ms_rest_azure-0.1.2/lib/ms_rest_azure/credentials/application_token_provider.rb:50:in `initialize'
E, [2016-02-23T22:34:01.425715 #64853] ERROR -- Kitchen: /Users/dobrien/.chefdk/gem/ruby/2.1.0/gems/kitchen-azurerm-0.2.6/lib/kitchen/driver/credentials.rb:33:in `new'
E, [2016-02-23T22:34:01.425728 #64853] ERROR -- Kitchen: /Users/dobrien/.chefdk/gem/ruby/2.1.0/gems/kitchen-azurerm-0.2.6/lib/kitchen/driver/credentials.rb:33:in `azure_credentials_for_subscription'
E, [2016-02-23T22:34:01.425740 #64853] ERROR -- Kitchen: /Users/dobrien/.chefdk/gem/ruby/2.1.0/gems/kitchen-azurerm-0.2.6/lib/kitchen/driver/azurerm.rb:208:in `destroy'
E, [2016-02-23T22:34:01.425752 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `public_send'
E, [2016-02-23T22:34:01.425763 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `block in perform_action'
E, [2016-02-23T22:34:01.425781 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
E, [2016-02-23T22:34:01.425793 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2016-02-23T22:34:01.425805 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
E, [2016-02-23T22:34:01.425817 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-02-23T22:34:01.425828 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
E, [2016-02-23T22:34:01.425839 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:424:in `perform_action'
E, [2016-02-23T22:34:01.425851 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:411:in `destroy_action'
E, [2016-02-23T22:34:01.425862 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2016-02-23T22:34:01.425873 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
E, [2016-02-23T22:34:01.425888 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
E, [2016-02-23T22:34:01.425899 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:171:in `destroy'
E, [2016-02-23T22:34:01.425911 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:187:in `block in test'
E, [2016-02-23T22:34:01.425922 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-02-23T22:34:01.425941 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:185:in `test'
E, [2016-02-23T22:34:01.425973 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
E, [2016-02-23T22:34:01.425985 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2016-02-23T22:34:01.425996 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
E, [2016-02-23T22:34:01.426007 #64853] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2016-02-23T22:34:01.426021 #64853] ERROR -- Kitchen: ----------------------
```
My `.kitchen.yml` file:
```
---
driver:
  name: azurerm

driver_config:
  subscription_id: 'SUBSCRIPTIONID'
  location: 'West Europe'
  machine_size: 'Standard_D1'

provisioner:
  name: chef_zero

platforms:
  - name: windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[kitchentesting::default]
    attributes:
```
Any idea?

**Comment by stuartpreston** [comment]
@davidobrien1985 Can you triple check your ~/.azure/credentials file and make sure it is saved as UTF8 and includes a line ```tenant_id = "your-tenant-id"``` (Tenant ID is a GUID).

**Comment by davidobrien1985** [comment]
After quadruple-checking everything and even learning some Ruby along the way I checked the `yml` stuff kitchen creates in its local repo `.kitchen` and there it had a file in it from the very first run which had a faulty credentials file.
I removed that and now it's working like a charm.

Thanks (it's late, nearly midnight, so this all is automatically forgiven!) ;)

**Comment by stuartpreston** [comment]
Glad you were able to get it working!
